version: "3.9"
services:
  backend:
    build: ./backend
    ports:
    - "80:5000"
    volumes:
    - ./server:/app
    environment:
      FLASK_ENV: development
  frontend:
    build: ./frontend
    ports:
      - "3000:5000" 
    volumes:
      - ./frontend:/user/src/app
    depends_on:
      - backend